### ISSUE TITLE
Unexpected message type 13 received from collector to provisioner.

### ISSUE THREAD

**Issue by laaurii00** [OpenLI-NZ/openli#107]
Hi,

During internal communications between the provisioner and the other elements (collector and mediator), the message ‘unexpected message type 13 received from collector’ appears on the screen. What does this mean, what is the reason and is there any solution? The installation of OpenLI in this case has been through packages:

```
sudo apt-get install apt-transport-https curl
curl -1sLf 'https://dl.cloudsmith.io/public/wand/libwandio/cfg/setup/bash.deb.sh' | sudo -E bash
curl -1sLf 'https://dl.cloudsmith.io/public/wand/libwandder/cfg/setup/bash.deb.sh' | sudo -E bash
curl -1sLf 'https://dl.cloudsmith.io/public/wand/libtrace/cfg/setup/bash.deb.sh' | sudo -E bash
curl -1sLf 'https://dl.cloudsmith.io/public/wand/openli/cfg/setup/bash.deb.sh' | sudo -E bash
sudo apt-get update


sudo apt-get install openli-provisioner
sudo apt-get install openli-collector
sudo apt-get install openli-mediator
```

Thank you in advance.

**Comment by salcock** [comment]
The most likely cause of this issue is misconfiguration of the `provisionerport` options in your collector and mediator configuration files.

For collectors, the `provisionerport` needs to match the port that is defined in the provisioner configuration file under the `clientport` option.

For mediators, the `provisionerport` needs to match the port that is defined in the provisioner configuration file under the `mediationport` option.

**Comment by laaurii00** [comment]
The actual Provisioner, Collector and Mediator configuration is:
Provisioner:

```
    clientaddr: Provisioner_ip_enpXs0
    clientport: 9001
    mediationaddr:  Provisioner_ip_enpXs0
    mediationport: 9002
    updateaddr:  Provisioner_ip_enpXs0
    updateport: 8080
    
    tlscert: /etc/openli/provisioner-crt.pem
    tlskey: /etc/openli/provisioner-key.pem
    tlsca: /etc/openli/ca-crt.pem
    
    intercept-config-file: /etc/openli/running-intercept-config.yaml
    voip-ignorecomfort: no
```
Collector:

```
      operatorid: WAND
      networkelementid: openli
      interceptpointid: col001
      encoderthreads: 2
      RMQenabled: false
      RMQname: "openli.nz"
      RMQpass: "XXX"
      
      inputs:
        - uri: enpXs0
          threads: 2
          hasher: radius
      
      provisioneraddr:  Provisioner_ip_enpXs0
      provisionerport: 9001
      
      etsitls: yes
      tlscert: /etc/openli/collector-crt.pem
      tlskey: /etc/openli/collector-key.pem
      tlsca: /etc/openli/ca-crt.pem
```
      
Mediator:

```
      operatorid: WAND
      mediatorid: 1
      provisioneraddr:  Provisioner_ip_enpXs0
      provisionerport: 9001
      listenaddr:  Mediator_ip_enpXs0
      listenport: 12009
      
      etsitls: yes
      
      tlscert: /etc/openli/mediator-crt.pem
      tlskey: /etc/openli/mediator-key.pem
      tlsca: /etc/openli/ca-crt.pem
      
      RMQenabled: true
      RMQname: "openli.nz"
      RMQpass: "XXXX"
      RMQSSL: false
      RMQheartbeatfreq: 0
      RMQinternalpass: "XXX"
```

From what I have learned from OpenLI, I believe that the configuration of the three elements is correct. Could there be another reason?
