### ISSUE TITLE
Issue with IP/VoIP Interception and `etsilive` Format Recognition in OpenLI Setup

### ISSUE THREAD

**Issue by laaurii00** [OpenLI-NZ/openli#108]
Hello OpenLI team,

I am currently working with an OpenLI deployment composed of four virtual machines: **LEA**, **Provisioner**, **Collector**, and **Mediator** (configured with `mediatorid: 1`). All OpenLI components were installed via RPM packages (https://github.com/OpenLI-NZ/openli/wiki/Installing-via-RPM) and are configured to communicate internally using classic TLS. The **Provisioner** exposes port `8080` for communication with the **LEA**.

The actual Provisioner, Collector and Mediator configuration is:
**Provisioner:**
```
    clientaddr: Provisioner_ip_enpXs0
    clientport: 9001
    mediationaddr:  Provisioner_ip_enpXs0
    mediationport: 9002
    updateaddr:  Provisioner_ip_enpXs0
    updateport: 8080
    
    tlscert: /etc/openli/provisioner-crt.pem
    tlskey: /etc/openli/provisioner-key.pem
    tlsca: /etc/openli/ca-crt.pem
    
    intercept-config-file: /etc/openli/running-intercept-config.yaml
    voip-ignorecomfort: no
```
**Collector:**
```
      operatorid: WAND
      networkelementid: openli
      interceptpointid: col001
      encoderthreads: 2
      RMQenabled: false
      RMQname: "openli.nz"
      RMQpass: "XXX"
      
      inputs:
        - uri: enpXs0
          threads: 2
          hasher: radius
      
      provisioneraddr:  Provisioner_ip_enpXs0
      provisionerport: 9001
      
      etsitls: yes
      tlscert: /etc/openli/collector-crt.pem
      tlskey: /etc/openli/collector-key.pem
      tlsca: /etc/openli/ca-crt.pem
      
```
**Mediator:**
```
      operatorid: WAND
      mediatorid: 1
      provisioneraddr:  Provisioner_ip_enpXs0
      provisionerport: 9001
      listenaddr:  Mediator_ip_enpXs0
      listenport: 12009
      
      etsitls: yes
      
      tlscert: /etc/openli/mediator-crt.pem
      tlskey: /etc/openli/mediator-key.pem
      tlsca: /etc/openli/ca-crt.pem
      
      RMQenabled: true
      RMQname: "openli.nz"
      RMQpass: "XXXX"
      RMQSSL: false
      RMQheartbeatfreq: 0
      RMQinternalpass: "XXX"
```

**The LEA has been configured with the following parameters:**
```json
[
  {
    "agencyid": "LEA_VM",
    "hi3address": "LEA_ip_enpXs0",
    "hi2address": "LEA_ip_enpXs0",
    "hi3port": "3030",
    "hi2port": "2020",
    "keepalivefreq": 300,
    "keepalivewait": 30
  }
]
```

The `ipinterface` and `voipinterface` are configured as follows:

```json
[
  {
    "liid": "TEST1",
    "authcc": "SP",
    "delivcc": "SP",
    "agencyid": "LEA_VM",
    "mediator": 1,
    "outputhandovers": 0,
    "payloadencryption": "none",
    "user": "roger",
    "accesstype": "fiber",
    "radiusident": "any"
  }
]
```

```json
[
  {
    "liid": "TEST1",
    "authcc": "SP",
    "delivcc": "SP",
    "agencyid": "LEA_VM",
    "mediator": 1,
    "outputhandovers": 0,
    "payloadencryption": "none",
    "siptargets": [
      {
        "username": "steve",
        "realm": "myrealm.com"
      }
    ]
  }
]
```

However, when attempting to activate IP or VoIP interception, I encounter the following issues:

1. When trying to monitor HI2 and HI3 traffic using `tracepktdump`:
   ```bash
   sudo tracepktdump etsilive:LEA_ip_enpXs0:3030
   sudo tracepktdump etsilive:LEA_ip_enpXs0:2020
   ```
   **I receive the error:**
   ```
   trace_create: Unknown format (etsilive)
   ```

2. If I instead capture traffic using `tcpdump`:
   ```bash
   sudo tcpdump -i any host LEA_ip_enpXs0 and port 2020 -w captH2.pcap
   sudo tcpdump -i any host LEA_ip_enpXs0 and port 3030 -w captH3.pcap
   ```
   and then replay it using:
   ```bash
   sudo tracereplay /pcap/tcpsip_voip.pcap ring:enpXs0
   sudo tracereplay /pcap/staticip.pcap ring:enpXs0
   ```
   nothing is received or processed.

**Questions:**

- What is required to enable support for the `etsilive` format in `tracepktdump`?
- Are there additional packages or configurations needed?
- What changes, if any, are required in the configuration files of the **Collector**, **Mediator**, or **Provisioner** to enable proper IP and VoIP interception?

Thank you very much for your support.

Best regards.
